# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2763c8b94c3a40d1f40bd9317e7cb84657d3f8e1d55873290ab7d656b43f8d6191af60e9a2f526d599560ce95a6c2545959c1e9243c27e3d9c26d74ca6363d92

test:
  secret_key_base: fd0676a16167e5e6ac75ff5124aaac6d50a71d47cfc6c217098936b657eeb48656373ee10f673b392ef28ed6a9b35f76216fb92a01603c3ff4e2a21b9d014faa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
